services:
  bun-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: OrderLink-AdminTool
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
