export const ENDPOINTS = {
  ADDRESSES: 'addresses',
  ADDRESS: (id: string | number) => `addresses/${id}`,
  CATEGORIES: 'categories',
  CATEGORY: (id: string | number) => `categories/${id}`,
  CUSTOMERS: 'customers',
  CUSTOMER: (ref: string | number) => `customers/${ref}`,
  CUSTOMER_DELETE: (ref: string | number) => `customers/${ref}/delete`,
  CUSTOMER_RESTORE: (ref: string | number) => `customers/${ref}/restore`,
  EMPLOYEES: 'employees',
  EMPLOYEE: (id: string | number) => `employees/${id}`,
  ORDERS: 'orders',
  ORDER: (id: string | number) => `orders/${id}`,
  PRODUCTS: 'products',
  PRODUCT: (id: string | number) => `products/${id}`,
  PRODUCT_HISTORY: (id: string | number) => `products/history/${id}`,
  ROUTES: 'routes',
  ROUTE: (id: string | number) => `routes/${id}`,
  PERMISSIONS: 'permissions',
  PERMISSION: (id: string | number) => `permissions/${id}`,
  SITE_CONFIG: 'siteConfig',
  SITE_CONFIG_ID: (id: string | number) => `siteConfig/${id}`,
  SUBSCRIPTIONS: 'subscriptions',
  SUBSCRIPTION_PAUSE: (id: string | number) => `subscriptions/${id}/pause`,
  SUBSCRIPTION_CANCEL: (id: string | number) => `subscriptions/${id}/cancel`,
  ROLES: 'roles',
  ROLE: (id: string | number) => `roles/${id}`,
  ROLES_ROLE_NAMES: 'roles/roleNames',
  AUTH_LOGIN: 'auth/signIn',
  AUTH_OTP: (tenantSlug: string, otp: number) =>
    `auth/otp/${tenantSlug}/${otp}`,
  OTP_RESEND: (id: string | number) => `otp/resend/${id}`,
  AUTH_RENEW_SESSION: 'auth/renewSession',
  EMPLOYEE_WITH_OTP: (id: string | number) => `employees/${id}?includeOtp=true`,
  GET_ME: 'employees/me',
  UPDATE_ME: 'employees/me',
  CHECK_OUT: 'billing/checkout',
} as const;

export type EndpointKey = keyof typeof ENDPOINTS;
