name: Build and Deploy Bun NextJS App

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Nimm VARS für „öffentliche“ Werte oder SECRETS, wenn du vorsichtig sein willst
      NEXT_PUBLIC_EXTERNAL_API: ${{ vars.NEXT_PUBLIC_EXTERNAL_API }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./admin-tool
          file: ./admin-tool/Dockerfile
          push: true
          tags: rechbe200163/orderlink-admintool:latest
